# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DollarLogger' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DollarLogger
  
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.3.0'
  
  target 'DollarLoggerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DollarLogger-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DollarLogger-tvOS

  target 'DollarLogger-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
